### ISSUE TITLE
打开程序插件启动失败

### ISSUE THREAD

**Issue by bambooslip** [dempe/simple-markdown-for-anki#2]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.19041

When loading Simple Markdown:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\\AppData\Roaming\Anki2\addons21\354124843\__init__.py", line 1, in <module>
    from . import markdown_converter
  File "C:\Users\\AppData\Roaming\Anki2\addons21\354124843\markdown_converter.py", line 82, in <module>
    if load_meta()['config']['automatic']:
KeyError: 'config'

**Comment by dempe** [comment]
https://github.com/dempe/simple-markdown-for-anki/issues/1

**Comment by dempe** [comment]
Hello, thanks for posting.  I have [replicated this issue](https://github.com/dempe/simple-markdown-for-anki/issues/1#issuecomment-2332111680) and am now investigating.
